apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alcmsft-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alcmsft-app
    spec:
      containers:
      - name: alcmsft-app
        image: alcmsftreg.azurecr.io/alcmsftapp:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: alcmsft-app
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: alcmsft-app